spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: server-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/yuan563421580/spring-cloud-demo.git
          search-paths: config-repos
          username: MyUserName
          password: MyPassword
server:
  port: 8888
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/