spring:
  application:
    name: server-provider
  main:
    allow-bean-definition-overriding: true
server:
  port: 8001
  #port: 8002
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/